// bytecodes: 63

static const label_t bytecodeLabels[] PROGMEM = {
	LABEL(INVOKESHORT),            //   0 java_lang_Thread_setStateAndSwitch_II
	LABEL(INVOKESHORT),            //   1 java_lang_Object__init__V
	LABEL(INVOKESHORT),            //   2 processing_hardware_arduino_cores_arduino_Arduino_delay_JV
	LABEL(INVOKESHORT),            //   3 processing_hardware_arduino_cores_arduino_Arduino_digitalWrite_IIV
	LABEL(INVOKESHORT),            //   4 processing_hardware_arduino_cores_arduino_Stream__init__V
	LABEL(INVOKESHORT),            //   5 java_lang_System_currentTimeMillis_J
	LABEL(INVOKESHORT),            //   6 processing_hardware_arduino_cores_arduino_ArduinoImpl_pinMode_BBV
	LABEL(INVOKESHORT),            //   7 processing_hardware_arduino_cores_arduino_Print__init__V
	LABEL(INVOKESHORT),            //   8 processing_examples__01_Basics_Blink_loop_V
	LABEL(INVOKESHORT),            //   9 java_lang_Throwable__init__Ljava_lang_String_V
	LABEL(INVOKESHORT),            //  10 processing_hardware_arduino_cores_arduino_HardwareSerial__init__V
	LABEL(INVOKESHORT),            //  11 java_lang_OutOfMemoryError__init__Ljava_lang_String_V
	LABEL(INVOKESHORT),            //  12 java_lang_Error__init__Ljava_lang_String_V
	LABEL(INVOKESHORT),            //  13 processing_hardware_arduino_cores_arduino_Arduino_pinMode_IIV
	LABEL(INVOKESHORT),            //  14 java_lang_Thread_currentThread_Ljava_lang_Thread
	LABEL(INVOKESHORT),            //  15 processing_examples__01_Basics_Blink_setup_V
	LABEL(INVOKESHORT),            //  16 haiku_vm_MicroKernel_clinitHaikuMagic_V
	LABEL(INVOKESHORT),            //  17 processing_hardware_arduino_cores_arduino_ArduinoImpl_delay_JV
	LABEL(INVOKESHORT),            //  18 processing_hardware_arduino_cores_arduino_ArduinoImpl_digitalWrite_BBV
	LABEL(INVOKESHORT),            //  19 java_lang_Thread_nap_JV
	LABEL(INVOKESHORT),            //  20 processing_examples__01_Basics_Blink__clinit__V
	LABEL(INVOKESHORT),            //  21 haiku_vm_MicroKernel__clinit__V
	LABEL(INVOKESHORT),            //  22 processing_hardware_arduino_cores_arduino_Print__clinit__V
	LABEL(INVOKESHORT),            //  23 processing_hardware_arduino_cores_arduino_Arduino__clinit__V
	LABEL(INVOKESHORT),            //  24 java_lang_Throwable_fillInStackTrace_Ljava_lang_Throwable
	LABEL(INVOKESHORT),            //  25 java_lang_Thread_stop_V
	LABEL(INVOKESHORT),            //  26 main_YLjava_lang_String
	LABEL(ARETURN),                //  27 ARETURN
	LABEL(BIPUSH),                 //  28 BIPUSH
	LABEL(LDC_S),                  //  29 LDC_S
	LABEL(DUP),                    //  30 DUP
	LABEL(LDC2_W_L),               //  31 LDC2_W_L
	LABEL(ALOAD_0),                //  32 ALOAD_0
	LABEL(ALOAD_0),                //  33 ALOAD_1
	LABEL(IF_ACMPEQ),              //  34 IF_ACMPEQ
	LABEL(GETFIELD_I),             //  35 GETFIELD_I
	LABEL(GETFIELD_L),             //  36 GETFIELD_L
	LABEL(GETSTATIC_B),            //  37 GETSTATIC_B
	LABEL(GETSTATIC_L),            //  38 GETSTATIC_L
	LABEL(GOTO),                   //  39 GOTO
	LABEL(LLOAD_0),                //  40 LLOAD_0
	LABEL(ASTORE_0),               //  41 ASTORE_1
	LABEL(IF_ICMPEQ),              //  42 IF_ICMPEQ
	LABEL(I2B),                    //  43 I2B
	LABEL(ICONST_0),               //  44 ICONST_0
	LABEL(ICONST_1),               //  45 ICONST_1
	LABEL(ICONST_M1),              //  46 ICONST_M1
	LABEL(ILOAD_0),                //  47 ILOAD_0
	LABEL(ILOAD_1),                //  48 ILOAD_1
	LABEL(INVOKESPECIAL),          //  49 INVOKESTATIC
	LABEL(INVOKEVIRTUAL),          //  50 INVOKEVIRTUAL
	LABEL(LADD),                   //  51 LADD
	LABEL(NEW),                    //  52 NEW
	LABEL(POP),                    //  53 POP
	LABEL(PUTFIELD_C),             //  54 PUTFIELD_C
	LABEL(PUTFIELD_I),             //  55 PUTFIELD_I
	LABEL(PUTFIELD_J),             //  56 PUTFIELD_J
	LABEL(PUTFIELD_L),             //  57 PUTFIELD_L
	LABEL(PUTSTATIC_B),            //  58 PUTSTATIC_B
	LABEL(PUTSTATIC_I),            //  59 PUTSTATIC_I
	LABEL(PUTSTATIC_L),            //  60 PUTSTATIC_L
	LABEL(RETURN),                 //  61 RETURN
	LABEL(SIPUSH),                 //  62 SIPUSH
};
