#define HAIKU_APP_BASE (D:\arduino-1.0.5\libraries\.)
#define HAIKU_APP_NAME (Blink)
#define HAIKU_CC (@echo Please use Arduino IDE for compile step)
#define HAIKU_CXX (@echo Please use Arduino IDE for compile step)
// Mapped '8' to 'HAIKU_CHAR_8'
#define HAIKU_Char (HAIKU_CHAR_8)
#define HAIKU_Config (arduinoIDE)
#define HAIKU_Extends (avr)
#define HAIKU_Extension (.hex)
#define HAIKU_GC (HAIKU_StopTheWorldGC)
#define HAIKU_HAIKUVM4C (./haikuVM)
#define HAIKU_HOME (D:\Entwicklung\haikuVM)
#define HAIKU_IncrementalGCSlice (10)
#define HAIKU_InitialMainThreadStackSize (142)
#define HAIKU_InitialOtherThreadStackSize (45)
#define HAIKU_PanicExceptions (NullPointerException | NoSuchMethodError | OutOfMemoryError | ClassCastException | InternalError)
#define HAIKU_PanicSupport (0)
#define HAIKU_LINKER (NONE)
#define HAIKU_MemorySize (((RAMEND-0x100) - 500))
#define HAIKU_MicroKernel (haiku.avr.lib.arduino.HaikuMicroKernel4ArduinoIDE)
// Mapped '16/32' to 'HAIKU_16_32'
#define HAIKU_Mode (HAIKU_16_32)
#define HAIKU_Output ($(HAIKU_APP_NAME)$(HAIKU_EXTENSION))
#define HAIKU_Target (arduinoIDE)
#define HAIKU_Threads (0)
#define HAIKU_Upload (@echo Please use Arduino IDE for compile and upload)
#define HAIKU_UserMain (justDefined)
#define HAIKU_VM_BASE (../../HaikuVM)
