package haiku.bcm;

public class GPIOConstants {
  // GPIO constant definitions, which appear to be the same across Pi boards
  public static final int GPFSEL0 =   0;     // GPIO Function Select 0
  public static final int GPFSEL1 =   1;     // GPIO Function Select 1
  public static final int GPFSEL2 =   2;     // GPIO Function Select 2
  public static final int GPFSEL3 =   3;     // GPIO Function Select 3
  public static final int GPFSEL4 =   4;     // GPIO Function Select 4
  public static final int GPFSEL5 =   5;     // GPIO Function Select 5

  public static final int GPSET0 =    7;     // GPIO Pin Output Set 0
  public static final int GPSET1 =    8;     // GPIO Pin Output Set 1

  public static final int GPCLR0 =    10;    // GPIO Pin Output Clear 0
  public static final int GPCLR1 =    11;    // GPIO Pin Output Clear 1

  public static final int GPLEV0 =    13;    // GPIO Pin Level 0
  public static final int GPLEV1 =    14;    // GPIO Pin Level 1

  public static final int GPEDS0 =    16;    // GPIO Pin Event Detect Status 0
  public static final int GPEDS1 =    17;    // GPIO Pin Event Detect Status 1

  public static final int GPREN0 =    19;    // GPIO Pin Rising Edge Detect Enable 0
  public static final int GPREN1 =    20;    // GPIO Pin Rising Edge Detect Enable 1

  public static final int GPFEN0 =    22;    // GPIO Pin Falling Edge Detect Enable 0
  public static final int GPFEN1 =    23;    // GPIO Pin Falling Edge Detect Enable 1

  public static final int GPHEN0 =    25;    // GPIO Pin High Detect Enable 0
  public static final int GPHEN1 =    26;    // GPIO Pin High Detect Enable 1

  public static final int GPLEN0 =    28;    // GPIO Pin Low Detect Enable 0
  public static final int GPLEN1 =    29;    // GPIO Pin Low Detect Enable 1

  public static final int GPAREN0 =   31;    // GPIO Pin Async. Rising Edge Detect 0
  public static final int GPAREN1 =   32;    // GPIO Pin Async. Rising Edge Detect 1

  public static final int GPAFEN0 =   34;    // GPIO Pin Async. Falling Edge Detect 0
  public static final int GPAFEN1 =   35;    // GPIO Pin Async. Falling Edge Detect 1

  public static final int GPPUD =     37;    // GPIO Pin Pull-up/down Enable
  public static final int GPPUDCLK0 = 38;    // GPIO Pin Pull-up/down Enable Clock 0
  public static final int GPPUDCLK1 = 39;    // GPIO Pin Pull-up/down Enable Clock 1

  public static final int FSEL0 =     0;     // Function Select pin 0
  public static final int FSEL1 =     3;     // Function Select pin 1
  public static final int FSEL2 =     6;     // Function Select pin 2
  public static final int FSEL3 =     9;     // Function Select pin 3
  public static final int FSEL4 =     12;    // Function Select pin 4
  public static final int FSEL5 =     15;    // Function Select pin 5
  public static final int FSEL6 =     18;    // Function Select pin 6
  public static final int FSEL7 =     21;    // Function Select pin 7
  public static final int FSEL8 =     24;    // Function Select pin 8
  public static final int FSEL9 =     27;    // Function Select pin 9
  public static final int FSEL10 =    0;     // Function Select pin 10
  public static final int FSEL11 =    3;     // Function Select pin 11
  public static final int FSEL12 =    6;     // Function Select pin 12
  public static final int FSEL13 =    9;     // Function Select pin 13
  public static final int FSEL14 =    12;    // Function Select pin 14
  public static final int FSEL15 =    15;    // Function Select pin 15
  public static final int FSEL16 =    18;    // Function Select pin 16
  public static final int FSEL17 =    21;    // Function Select pin 17
  public static final int FSEL18 =    24;    // Function Select pin 18
  public static final int FSEL19 =    27;    // Function Select pin 19
  public static final int FSEL20 =    0;     // Function Select pin 20
  public static final int FSEL21 =    3;     // Function Select pin 21
  public static final int FSEL22 =    6;     // Function Select pin 22
  public static final int FSEL23 =    9;     // Function Select pin 23
  public static final int FSEL24 =    12;    // Function Select pin 24
  public static final int FSEL25 =    15;    // Function Select pin 25
  public static final int FSEL26 =    18;    // Function Select pin 26
  public static final int FSEL27 =    21;    // Function Select pin 27
  public static final int FSEL28 =    24;    // Function Select pin 28
  public static final int FSEL29 =    27;    // Function Select pin 29
  public static final int FSEL30 =    0;     // Function Select pin 30
  public static final int FSEL31 =    3;     // Function Select pin 31
  public static final int FSEL32 =    6;     // Function Select pin 32
  public static final int FSEL33 =    9;     // Function Select pin 33
  public static final int FSEL34 =    12;    // Function Select pin 34
  public static final int FSEL35 =    15;    // Function Select pin 35
  public static final int FSEL36 =    18;    // Function Select pin 36
  public static final int FSEL37 =    21;    // Function Select pin 37
  public static final int FSEL38 =    24;    // Function Select pin 38
  public static final int FSEL39 =    27;    // Function Select pin 39
  public static final int FSEL40 =    0;     // Function Select pin 40
  public static final int FSEL41 =    3;     // Function Select pin 41
  public static final int FSEL42 =    6;     // Function Select pin 42
  public static final int FSEL43 =    9;     // Function Select pin 43
  public static final int FSEL44 =    12;    // Function Select pin 44
  public static final int FSEL45 =    15;    // Function Select pin 45
  public static final int FSEL46 =    18;    // Function Select pin 46
  public static final int FSEL47 =    21;    // Function Select pin 47
  public static final int FSEL48 =    24;    // Function Select pin 48
  public static final int FSEL49 =    27;    // Function Select pin 49
  public static final int FSEL50 =    0;     // Function Select pin 50
  public static final int FSEL51 =    3;     // Function Select pin 51
  public static final int FSEL52 =    6;     // Function Select pin 52
  public static final int FSEL53 =    9;     // Function Select pin 53

  public static final int GPINPUT   = 0;  // GPIO Pin is an input 0b000
  public static final int GPOUTPUT  = 1;  // GPIO Pin is an output 0b001
  public static final int GPAF0     = 4;  // GPIO Pin takes alternate function 0 0b100
  public static final int GPAF1     = 5;  // GPIO Pin takes alternate function 1 0b101
  public static final int GPAF2     = 6;  // GPIO Pin takes alternate function 2 0b110
  public static final int GPAF3     = 7;  // GPIO Pin takes alternate function 3 0b111
  public static final int GPAF4     = 3;  // GPIO Pin takes alternate function 4 0b011
  public static final int GPAF5     = 2;  // GPIO Pin takes alternate function 5 0b010 

  public static final int SET0  =   0;    // GPIO Pin 0 Output Set Registers
  public static final int SET1  =   1;    // GPIO Pin 1 Output Set Registers
  public static final int SET2  =   2;    // GPIO Pin 2 Output Set Registers
  public static final int SET3  =   3;    // GPIO Pin 3 Output Set Registers
  public static final int SET4  =   4;    // GPIO Pin 4 Output Set Registers
  public static final int SET5  =   5;    // GPIO Pin 5 Output Set Registers
  public static final int SET6  =   6;    // GPIO Pin 6 Output Set Registers
  public static final int SET7  =   7;    // GPIO Pin 7 Output Set Registers
  public static final int SET8  =   8;    // GPIO Pin 8 Output Set Registers
  public static final int SET9  =   9;    // GPIO Pin 9 Output Set Registers
  public static final int SET10 =  10;    // GPIO Pin 10 Output Set Registers
  public static final int SET11 =  11;    // GPIO Pin 11 Output Set Registers
  public static final int SET12 =  12;    // GPIO Pin 12 Output Set Registers
  public static final int SET13 =  13;    // GPIO Pin 13 Output Set Registers
  public static final int SET14 =  14;    // GPIO Pin 14 Output Set Registers
  public static final int SET15 =  15;    // GPIO Pin 15 Output Set Registers
  public static final int SET16 =  16;    // GPIO Pin 16 Output Set Registers
  public static final int SET17 =  17;    // GPIO Pin 17 Output Set Registers
  public static final int SET18 =  18;    // GPIO Pin 18 Output Set Registers
  public static final int SET19 =  19;    // GPIO Pin 19 Output Set Registers
  public static final int SET20 =  20;    // GPIO Pin 20 Output Set Registers
  public static final int SET21 =  21;    // GPIO Pin 21 Output Set Registers
  public static final int SET22 =  22;    // GPIO Pin 22 Output Set Registers
  public static final int SET23 =  23;    // GPIO Pin 23 Output Set Registers
  public static final int SET24 =  24;    // GPIO Pin 24 Output Set Registers
  public static final int SET25 =  25;    // GPIO Pin 25 Output Set Registers
  public static final int SET26 =  26;    // GPIO Pin 26 Output Set Registers
  public static final int SET27 =  27;    // GPIO Pin 27 Output Set Registers
  public static final int SET28 =  28;    // GPIO Pin 28 Output Set Registers
  public static final int SET29 =  29;    // GPIO Pin 29 Output Set Registers
  public static final int SET30 =  30;    // GPIO Pin 30 Output Set Registers
  public static final int SET31 =  31;    // GPIO Pin 31 Output Set Registers
  public static final int SET32 =   0;    // GPIO Pin 32 Output Set Registers
  public static final int SET33 =   1;    // GPIO Pin 33 Output Set Registers
  public static final int SET34 =   2;    // GPIO Pin 34 Output Set Registers
  public static final int SET35 =   3;    // GPIO Pin 35 Output Set Registers
  public static final int SET36 =   4;    // GPIO Pin 36 Output Set Registers
  public static final int SET37 =   5;    // GPIO Pin 37 Output Set Registers
  public static final int SET38 =   6;    // GPIO Pin 38 Output Set Registers
  public static final int SET39 =   7;    // GPIO Pin 39 Output Set Registers
  public static final int SET40 =   8;    // GPIO Pin 40 Output Set Registers
  public static final int SET41 =   9;    // GPIO Pin 41 Output Set Registers
  public static final int SET42 =  10;    // GPIO Pin 42 Output Set Registers
  public static final int SET43 =  11;    // GPIO Pin 43 Output Set Registers
  public static final int SET44 =  12;    // GPIO Pin 44 Output Set Registers
  public static final int SET45 =  13;    // GPIO Pin 45 Output Set Registers
  public static final int SET46 =  14;    // GPIO Pin 46 Output Set Registers
  public static final int SET47 =  15;    // GPIO Pin 47 Output Set Registers
  public static final int SET48 =  16;    // GPIO Pin 48 Output Set Registers
  public static final int SET49 =  17;    // GPIO Pin 49 Output Set Registers
  public static final int SET50 =  18;    // GPIO Pin 50 Output Set Registers
  public static final int SET51 =  19;    // GPIO Pin 51 Output Set Registers
  public static final int SET52 =  20;    // GPIO Pin 52 Output Set Registers
  public static final int SET53 =  21;    // GPIO Pin 53 Output Set Registers

  public static final int CLR0  =   0;    // GPIO Pin 0 Output Clear Registers
  public static final int CLR1  =   1;    // GPIO Pin 1 Output Clear Registers
  public static final int CLR2  =   2;    // GPIO Pin 2 Output Clear Registers
  public static final int CLR3  =   3;    // GPIO Pin 3 Output Clear Registers
  public static final int CLR4  =   4;    // GPIO Pin 4 Output Clear Registers
  public static final int CLR5  =   5;    // GPIO Pin 5 Output Clear Registers
  public static final int CLR6  =   6;    // GPIO Pin 6 Output Clear Registers
  public static final int CLR7  =   7;    // GPIO Pin 7 Output Clear Registers
  public static final int CLR8  =   8;    // GPIO Pin 8 Output Clear Registers
  public static final int CLR9  =   9;    // GPIO Pin 9 Output Clear Registers
  public static final int CLR10 =  10;    // GPIO Pin 10 Output Clear Registers
  public static final int CLR11 =  11;    // GPIO Pin 11 Output Clear Registers
  public static final int CLR12 =  12;    // GPIO Pin 12 Output Clear Registers
  public static final int CLR13 =  13;    // GPIO Pin 13 Output Clear Registers
  public static final int CLR14 =  14;    // GPIO Pin 14 Output Clear Registers
  public static final int CLR15 =  15;    // GPIO Pin 15 Output Clear Registers
  public static final int CLR16 =  16;    // GPIO Pin 16 Output Clear Registers
  public static final int CLR17 =  17;    // GPIO Pin 17 Output Clear Registers
  public static final int CLR18 =  18;    // GPIO Pin 18 Output Clear Registers
  public static final int CLR19 =  19;    // GPIO Pin 19 Output Clear Registers
  public static final int CLR20 =  20;    // GPIO Pin 20 Output Clear Registers
  public static final int CLR21 =  21;    // GPIO Pin 21 Output Clear Registers
  public static final int CLR22 =  22;    // GPIO Pin 22 Output Clear Registers
  public static final int CLR23 =  23;    // GPIO Pin 23 Output Clear Registers
  public static final int CLR24 =  24;    // GPIO Pin 24 Output Clear Registers
  public static final int CLR25 =  25;    // GPIO Pin 25 Output Clear Registers
  public static final int CLR26 =  26;    // GPIO Pin 26 Output Clear Registers
  public static final int CLR27 =  27;    // GPIO Pin 27 Output Clear Registers
  public static final int CLR28 =  28;    // GPIO Pin 28 Output Clear Registers
  public static final int CLR29 =  29;    // GPIO Pin 29 Output Clear Registers
  public static final int CLR30 =  30;    // GPIO Pin 30 Output Clear Registers
  public static final int CLR31 =  31;    // GPIO Pin 31 Output Clear Registers
  public static final int CLR32 =   0;    // GPIO Pin 32 Output Clear Registers
  public static final int CLR33 =   1;    // GPIO Pin 33 Output Clear Registers
  public static final int CLR34 =   2;    // GPIO Pin 34 Output Clear Registers
  public static final int CLR35 =   3;    // GPIO Pin 35 Output Clear Registers
  public static final int CLR36 =   4;    // GPIO Pin 36 Output Clear Registers
  public static final int CLR37 =   5;    // GPIO Pin 37 Output Clear Registers
  public static final int CLR38 =   6;    // GPIO Pin 38 Output Clear Registers
  public static final int CLR39 =   7;    // GPIO Pin 39 Output Clear Registers
  public static final int CLR40 =   8;    // GPIO Pin 40 Output Clear Registers
  public static final int CLR41 =   9;    // GPIO Pin 41 Output Clear Registers
  public static final int CLR42 =  10;    // GPIO Pin 42 Output Clear Registers
  public static final int CLR43 =  11;    // GPIO Pin 43 Output Clear Registers
  public static final int CLR44 =  12;    // GPIO Pin 44 Output Clear Registers
  public static final int CLR45 =  13;    // GPIO Pin 45 Output Clear Registers
  public static final int CLR46 =  14;    // GPIO Pin 46 Output Clear Registers
  public static final int CLR47 =  15;    // GPIO Pin 47 Output Clear Registers
  public static final int CLR48 =  16;    // GPIO Pin 48 Output Clear Registers
  public static final int CLR49 =  17;    // GPIO Pin 49 Output Clear Registers
  public static final int CLR50 =  18;    // GPIO Pin 50 Output Clear Registers
  public static final int CLR51 =  19;    // GPIO Pin 51 Output Clear Registers
  public static final int CLR52 =  20;    // GPIO Pin 52 Output Clear Registers
  public static final int CLR53 =  21;    // GPIO Pin 53 Output Clear Registers  
}